service: my-serverless-app

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 128
  timeout: 10
  stage: production
  region: eu-central-1

functions:
  api:
    handler: lambda.universal
    events:
      - http: ANY {proxy+}
      - http: ANY /
# Add deploy script to package.json:
# "scripts": {
#  "start": "nodemon local.js",
#  "deploy": "serverless deploy"
# },
